Refine project and Add AutoLogin
skygear-demo/skygear-react-google-login pull request #6
Opened 2018-07-11 16:04 UTC by bryanchun

Resolve #2, #3, #4, #5.

Please note that as I wanted to use `Promise.all` to confirm that all promises are resolved so that I can group all the `then` and `catch` actions into one block, this worked for `componentDidMount` but failed at `this.onLogin`. Here, the promises must be run sequentially but there is no easily understandable vanilla code that does the same as `Promise.series` to synchronise the calls, that's why I resorted to nested promises.

2018-08-01 03:57 UTC, Steven-Chan requested changes

2018-08-01 03:57 UTC, Steven-Chan commented on src/App.js
> +    };
You can run promises in series with:

```js
skygear.auth.loginOAuthProviderWithPopup(xxx)
  .then((xxx) => {
     // xxxx
    return skygear.auth. getOAuthProviderProfiles();
  }).then((xxx) => {
    // xxx
  })
  .catch((xxx) => {
    // xxx;
  });
```

2018-08-01 03:57 UTC, Steven-Chan commented on src/App.js
> +    };
If you don't return a promise in the `then` function, the next `then` function would be executed immediately.

So your updated version runs into the same problem of the old code.

2018-08-03 01:21 UTC, bryanchun commented on src/App.js
> +    };
Thank you for the correction. I am not yet familiar with promises and the reason I tried to use nested promises (with hesitation) was I didn't realise I can get the resolved `value` of the second promise in the second `then`'s callback parameter. Now I know, and I will change accordingly.

2018-08-03 05:24 UTC, bryanchun reviewed
request for review

2018-08-06 08:09 UTC, Steven-Chan approved these changes

2018-08-06 08:10 UTC, merged